-- 코드를 입력하세요
SELECT B.BOOK_ID, A.AUTHOR_NAME, DATE_FORMAT(B.PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM AUTHOR AS A
INNER JOIN (
    SELECT BOOK_ID, AUTHOR_ID, PUBLISHED_DATE
    FROM BOOK
    WHERE CATEGORY LIKE '경제'
) AS B
ON A.AUTHOR_ID = B.AUTHOR_ID
ORDER BY B.PUBLISHED_DATE ASC;