-- 코드를 입력하세요
SELECT A.HOUR, COUNT(*) AS COUNT
FROM (
    SELECT HOUR(DATETIME) AS HOUR, ANIMAL_ID
    FROM ANIMAL_OUTS
    WHERE HOUR(DATETIME) >= 9 AND HOUR(DATETIME) < 20
) AS A
GROUP BY A.HOUR
ORDER BY A.HOUR ASC